<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Created by Kris Molendyke</string>
	<key>fileTypes</key>
	<array>
		<string>js</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\bfunction\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>mongoDB (JavaScript)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rawKeys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singleQuotedKeys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doubleQuotedKeys</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singleQuotedVals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doubleQuotedVals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>doubleQuotedKeys</key>
		<dict>
			<key>match</key>
			<string>"\w+(\.\w+)*"</string>
			<key>name</key>
			<string>string.quoted.double.js.mongodb</string>
		</dict>
		<key>doubleQuotedVals</key>
		<dict>
			<key>match</key>
			<string>"\w+(\.\w+)*"</string>
			<key>name</key>
			<string>string.quoted.double.js.mongodb</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\$(gt|lt|in|nin|all|mod|exists|type|elemMatch|not|where|or|inc|set|unset|push|pushAll|addToSet|each|pop|pull|pullAll|size|ne|gte|lte)\s*:</string>
			<key>name</key>
			<string>keyword.operator.js.mongodb</string>
		</dict>
		<key>rawKeys</key>
		<dict>
			<key>match</key>
			<string>\w+(\.\w+)*\s*:</string>
			<key>name</key>
			<string>keyword.other.js.mongodb</string>
		</dict>
		<key>singleQuotedKeys</key>
		<dict>
			<key>match</key>
			<string>'\w+(\.\w+)*'</string>
			<key>name</key>
			<string>string.quoted.single.js.mongodb</string>
		</dict>
		<key>singleQuotedVals</key>
		<dict>
			<key>match</key>
			<string>'\w+(\.\w+)*'</string>
			<key>name</key>
			<string>string.quoted.single.js.mongodb</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.mongodb</string>
	<key>uuid</key>
	<string>13436AF8-3CEA-4DB0-A6DE-3FE13DB1F0BB</string>
</dict>
</plist>
